In [1]:
import pandas as pd

In [3]:

dict1={
 "name":['harry','rohan','subh'],
 "marks":[65,98,41],
 "city":['Kolkata','Mumbai','Delhi']
}

In [5]:
df=pd.DataFrame(dict1)

In [7]:
df

    name  marks     city
0  harry     65  Kolkata
1  rohan     98   Mumbai
2   subh     41    Delhi

In [13]:
df.to_csv('std.csv',index=False)

In [15]:
df.describe()

           marks
count   3.000000
mean   68.000000
std    28.618176
min    41.000000
25%    53.000000
50%    65.000000
75%    81.500000
max    98.000000

In [23]:
df=pd.read_csv('train_1.csv')

In [25]:
df

   Train No  Speed       City
0     12125     50    Kolkata
1     21541     21      Delhi
2    211232     25      Patna
3   2121212     23  Hyderabad